name: scheduled-build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST ${{ secrets.BUILD_URL }}